// Code generated by mockery v1.0.0
package mocks

import app "github.com/ksonnet/ksonnet/metadata/app"
import mock "github.com/stretchr/testify/mock"

// App is an autogenerated mock type for the App type
type App struct {
	mock.Mock
}

// AddEnvironment provides a mock function with given fields: name, k8sSpecFlag, spec
func (_m *App) AddEnvironment(name string, k8sSpecFlag string, spec *app.EnvironmentSpec) error {
	ret := _m.Called(name, k8sSpecFlag, spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *app.EnvironmentSpec) error); ok {
		r0 = rf(name, k8sSpecFlag, spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Environment provides a mock function with given fields: name
func (_m *App) Environment(name string) (*app.EnvironmentSpec, error) {
	ret := _m.Called(name)

	var r0 *app.EnvironmentSpec
	if rf, ok := ret.Get(0).(func(string) *app.EnvironmentSpec); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.EnvironmentSpec)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Environments provides a mock function with given fields:
func (_m *App) Environments() (app.EnvironmentSpecs, error) {
	ret := _m.Called()

	var r0 app.EnvironmentSpecs
	if rf, ok := ret.Get(0).(func() app.EnvironmentSpecs); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(app.EnvironmentSpecs)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *App) Init() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LibPath provides a mock function with given fields: envName
func (_m *App) LibPath(envName string) (string, error) {
	ret := _m.Called(envName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(envName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(envName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Libraries provides a mock function with given fields:
func (_m *App) Libraries() app.LibraryRefSpecs {
	ret := _m.Called()

	var r0 app.LibraryRefSpecs
	if rf, ok := ret.Get(0).(func() app.LibraryRefSpecs); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(app.LibraryRefSpecs)
		}
	}

	return r0
}

// Registries provides a mock function with given fields:
func (_m *App) Registries() app.RegistryRefSpecs {
	ret := _m.Called()

	var r0 app.RegistryRefSpecs
	if rf, ok := ret.Get(0).(func() app.RegistryRefSpecs); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(app.RegistryRefSpecs)
		}
	}

	return r0
}

// RemoveEnvironment provides a mock function with given fields: name
func (_m *App) RemoveEnvironment(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upgrade provides a mock function with given fields: dryRun
func (_m *App) Upgrade(dryRun bool) error {
	ret := _m.Called(dryRun)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(dryRun)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
