// Copyright 2018 The ksonnet authors
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import app "github.com/ksonnet/ksonnet/pkg/app"
import mock "github.com/stretchr/testify/mock"
import registry "github.com/ksonnet/ksonnet/pkg/registry"

// Setter is an autogenerated mock type for the Setter type
type Setter struct {
	mock.Mock
}

// FetchRegistrySpec provides a mock function with given fields:
func (_m *Setter) FetchRegistrySpec() (*registry.Spec, error) {
	ret := _m.Called()

	var r0 *registry.Spec
	if rf, ok := ret.Get(0).(func() *registry.Spec); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.Spec)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeRegistryConfig provides a mock function with given fields:
func (_m *Setter) MakeRegistryConfig() *app.RegistryConfig030 {
	ret := _m.Called()

	var r0 *app.RegistryConfig030
	if rf, ok := ret.Get(0).(func() *app.RegistryConfig030); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.RegistryConfig030)
		}
	}

	return r0
}

// SetURI provides a mock function with given fields: uri
func (_m *Setter) SetURI(uri string) error {
	ret := _m.Called(uri)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(uri)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
