// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import app "github.com/ksonnet/ksonnet/pkg/app"
import mock "github.com/stretchr/testify/mock"
import registry "github.com/ksonnet/ksonnet/pkg/registry"

// Setter is an autogenerated mock type for the Setter type
type Setter struct {
	mock.Mock
}

// FetchRegistrySpec provides a mock function with given fields:
func (_m *Setter) FetchRegistrySpec() (*registry.Spec, error) {
	ret := _m.Called()

	var r0 *registry.Spec
	if rf, ok := ret.Get(0).(func() *registry.Spec); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.Spec)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeRegistryConfig provides a mock function with given fields:
func (_m *Setter) MakeRegistryConfig() *app.RegistryConfig {
	ret := _m.Called()

	var r0 *app.RegistryConfig
	if rf, ok := ret.Get(0).(func() *app.RegistryConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.RegistryConfig)
		}
	}

	return r0
}

// SetURI provides a mock function with given fields: uri
func (_m *Setter) SetURI(uri string) error {
	ret := _m.Called(uri)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(uri)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
