// Copyright 2018 The ksonnet authors
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Code generated by mockery v1.0.0
package mocks

import env "github.com/ksonnet/ksonnet/env"
import mock "github.com/stretchr/testify/mock"

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// Rename provides a mock function with given fields: from, to, config
func (_m *Manager) Rename(from string, to string, config env.RenameConfig) error {
	ret := _m.Called(from, to, config)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, env.RenameConfig) error); ok {
		r0 = rf(from, to, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
