// Copyright 2018 The ksonnet authors
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Code generated by "stringer -type=initName"; DO NOT EDIT.

package cmd

import "strconv"

const _initName_name = "actionApplyactionComponentListactionComponentNameactionDeleteactionDiffactionEnvAddactionEnvDescribeactionEnvListactionEnvRmactionEnvSetactionEnvTargetsactionImportactionInitactionNsCreateactionNsListactionParamDiffactionParamListactionParamSetactionPkgDescribeactionPkgInstallactionPkgListactionPrototypeDescribeactionPrototypeListactionPrototypePreviewactionPrototypeSearchactionPrototypeUseactionRegistryAddactionRegistryDescribeactionRegistryListactionShowactionUpgradeactionValidate"

var _initName_index = [...]uint16{0, 11, 30, 49, 61, 71, 83, 100, 113, 124, 136, 152, 164, 174, 188, 200, 215, 230, 244, 261, 277, 290, 313, 332, 354, 375, 393, 410, 432, 450, 460, 473, 487}

func (i initName) String() string {
	if i < 0 || i >= initName(len(_initName_index)-1) {
		return "initName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _initName_name[_initName_index[i]:_initName_index[i+1]]
}
