// Code generated by "stringer -type=initName"; DO NOT EDIT.

package cmd

import "strconv"

const _initName_name = "actionApplyactionComponentListactionComponentRmactionDeleteactionDiffactionEnvAddactionEnvDescribeactionEnvListactionEnvRmactionEnvSetactionEnvTargetsactionImportactionInitactionModuleCreateactionModuleListactionParamDiffactionParamListactionParamSetactionPkgDescribeactionPkgInstallactionPkgListactionPrototypeDescribeactionPrototypeListactionPrototypePreviewactionPrototypeSearchactionPrototypeUseactionRegistryAddactionRegistryDescribeactionRegistryListactionShowactionUpgradeactionValidate"

var _initName_index = [...]uint16{0, 11, 30, 47, 59, 69, 81, 98, 111, 122, 134, 150, 162, 172, 190, 206, 221, 236, 250, 267, 283, 296, 319, 338, 360, 381, 399, 416, 438, 456, 466, 479, 493}

func (i initName) String() string {
	if i < 0 || i >= initName(len(_initName_index)-1) {
		return "initName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _initName_name[_initName_index[i]:_initName_index[i+1]]
}
