// Copyright 2018 The ksonnet authors
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import app "github.com/ksonnet/ksonnet/pkg/app"
import component "github.com/ksonnet/ksonnet/pkg/component"
import mock "github.com/stretchr/testify/mock"

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// Component provides a mock function with given fields: ksApp, module, componentName
func (_m *Manager) Component(ksApp app.App, module string, componentName string) (component.Component, error) {
	ret := _m.Called(ksApp, module, componentName)

	var r0 component.Component
	if rf, ok := ret.Get(0).(func(app.App, string, string) component.Component); ok {
		r0 = rf(ksApp, module, componentName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(component.Component)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(app.App, string, string) error); ok {
		r1 = rf(ksApp, module, componentName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Components provides a mock function with given fields: ksApp, module
func (_m *Manager) Components(ksApp app.App, module string) ([]component.Component, error) {
	ret := _m.Called(ksApp, module)

	var r0 []component.Component
	if rf, ok := ret.Get(0).(func(app.App, string) []component.Component); ok {
		r0 = rf(ksApp, module)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]component.Component)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(app.App, string) error); ok {
		r1 = rf(ksApp, module)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateModule provides a mock function with given fields: ksApp, name
func (_m *Manager) CreateModule(ksApp app.App, name string) error {
	ret := _m.Called(ksApp, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(app.App, string) error); ok {
		r0 = rf(ksApp, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Module provides a mock function with given fields: ksApp, moduleName
func (_m *Manager) Module(ksApp app.App, moduleName string) (component.Module, error) {
	ret := _m.Called(ksApp, moduleName)

	var r0 component.Module
	if rf, ok := ret.Get(0).(func(app.App, string) component.Module); ok {
		r0 = rf(ksApp, moduleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(component.Module)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(app.App, string) error); ok {
		r1 = rf(ksApp, moduleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Modules provides a mock function with given fields: ksApp, envName
func (_m *Manager) Modules(ksApp app.App, envName string) ([]component.Module, error) {
	ret := _m.Called(ksApp, envName)

	var r0 []component.Module
	if rf, ok := ret.Get(0).(func(app.App, string) []component.Module); ok {
		r0 = rf(ksApp, envName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]component.Module)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(app.App, string) error); ok {
		r1 = rf(ksApp, envName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
